### PR TITLE
Added spectrum allocations for Bulgaria.

### PR DESCRIPTION
**Pull request by ivaylobelchev**

### CODE REVIEW

**Comment by olkitu** [comment]
There is error in json validation. Please fix syntax to meet schema and push again changes. Check here format: https://github.com/olkitu/Mobilespectrum/wiki/JSON-data-format

**Comment by ivaylobelchev** [comment]
I wanted to get the latest updates from the main branch but I think I accidentaly triggered a new valudation. I will try to find my mistake in the JSON tomorrow. Are the "arfcn" and Valid's "start" fields mandatory?

**Comment by ivaylobelchev** [comment]
I reordered the operators within each band and I believe this is what was causing the issue last time. Could you please approve the workflow?

**Comment by olkitu** [comment]
Still jsonvalidation failed. Make sure it match as required schema,. You can also run test locally: https://github.com/olkitu/Mobilespectrum/blob/main/CONTRIBUTING.md#adding-new-data-and-update-exist

**Comment by olkitu** [comment]
image

Please set correct background color to every network. I'm sure all networks should not use same color. I will revert merge.

**Pull request merged**
